### PR TITLE
Fix labels html labels and identical labels

### LINKED ISSUE #69: Boxplots for comparison of sets with same label shows just one set
If two sets with the same label are compared, only one boxplot is shown:
image

### PR DESCRIPTION
**Pull request by keckelt**
Fixes #69 and #71

HTML codes in set labels, e.g. `&#8804`, was not displayed properly (#71).
Instead of inserting text with d3's `.text()` this PR switches to `.html()` in order to display these properly.

Also, the boxplot for numerical set comparisons showed only one plot if the labels were identical (#69). To circumvent that, I( simply add a space with zero width to the second label so that they are no longer identical.

image

### CODE REVIEW

File: src/measure_visualization/BoxPlot.ts [hunk 1]
```diff
@@ -183,6 +183,8 @@ export class BoxPlot implements IMeasureVisualization {
       .attr('class', 'x axis')
       .attr('transform', 'translate(0,' + (height  + margin.top + 10) + ')')
       .call(xAxis);
+
+    svgFigureGroup.selectAll('.x.axis .tick text').html((d) => d);
```
Comment (keckelt) [inline src/measure_visualization/BoxPlot.ts:187]: Tick labels are text by default. This translates any html codes.

**Comment by keckelt** [comment]
Hi @oltionchampari, @anita-steiner, @dvvanessastoiber!

Could you have a look at the PR?

**Review by dvvanessastoiber — APPROVED** [review]
Works in my tests :+1: . The html labels are displayed correctly and in case of identical labels, two boxplots are shown. I could reproduce this behavior proved by this screenshot:
image
